### ISSUE TITLE
Table border alignment

### ISSUE THREAD

**Issue by lnicola** [peterheesterman/chit#17]
![image](https://user-images.githubusercontent.com/308347/55666559-6fa61600-5859-11e9-8cd5-1df6015ccc85.png)

Gnome Terminal on Arch Linux

**Comment by peterheesterman** [comment]
Thanks for this!

The Latest versions lines was just a bug, the star line was a slightly larger issue.  

I decided that i would just remove edges entirely to solve both these issues. Not sure why i put them in to begin with as they don't provide extra clarity. The 🌟emoji is being rendered with different widths in different terminals - i couldn't think of an easy fix for this or set the character width so i have just avoided the issue. 😁

Just for learning sake do you know a good way of dealing with this issue by chance? I will have to delve into how other people do it some time with other tools. 🤔

**Comment by lnicola** [comment]
Yeah, it looks much better now :smile:.

> Just for learning sake do you know a good way of dealing with this issue by chance? I will have to delve into how other people do it some time with other tools.

Ugh, no, I don't. AFAIK there is a concept of width in Unicode, but it's not actually related to the column width. In practice, the results will also depend on the font for things like the gendered emoji or those with skin tones, eg. 👩‍🔬 vs.

![image](https://user-images.githubusercontent.com/308347/55785277-cb230e80-5aba-11e9-8e02-76d6296bf2ab.png)

I think I would have simply used some yellow asterisks instead.

**Comment by peterheesterman** [comment]
@lnicola Ok interesting, I had a read of this (https://github.com/unicode-rs/unicode-width) and related/linked pages but couldn't find a solution. 🤷‍♂️ 

I was going to use something from here https://en.wikipedia.org/wiki/Star_(glyph) but it didn't look nice all all. 

Thanks again for raising issues and making suggestions!
