### ISSUE TITLE
(feat) I want to see alternatives to the crate that i am looking up

### ISSUE THREAD

**Issue by peterheesterman** [peterheesterman/chit#30]
**Is your feature request related to a problem? Please describe.**

I have a hard time knowing if the crate i am using is the most recent/recommended crate for something that i am trying to achieve

**Describe the solution you'd like**
I want chit to tell me alternatives for a given crate when i chit it.

**Describe alternatives you've considered**

The alternatives are to look at blog posts and find the info there. This should centralise it. 

**Additional context**
Suggested by a reddit user (BoastfulSquirrel)

**Comment by lnicola** [comment]
You could manually curate some from [here](https://github.com/rust-unofficial/awesome-rust/blob/master/README.md), but I don't think it's worth it.

**Comment by peterheesterman** [comment]
I like this as a way to just test if people care. Might need to get a more scalable way later on but we shall see. I am gonna shove it in here and use it from in chit. **https://github.com/peterheesterman/alt-rs** 

When i have some time i might do the top 100 from `rust-unofficial/awesome-rust` and see if people care enough to contribute by putting in a call to action if there is a crate without alternative/options listed. 😂

**Comment by lnicola** [comment]
I'm confused, why is that a Rust crate? Wouldn't it make sense to have a data file (like a JSON) with crates and their alternatives?

**Comment by peterheesterman** [comment]
I was thinking it would be something simple like that yes. I guess i can move it out of chit if i want to use if for something else one day, no need to make another crate. 🤷‍♂️

**Comment by lnicola** [comment]
It might be worth changing the format to define groups instead of alternatives to specific crates. Right now there's a lot of duplication, and adding a new crate to a group requires updating a lot of entries.

**Comment by peterheesterman** [comment]
Good idea, i will change it that sometime before publishing a new version. I wrote a tool to generate these from sets initially, should have tipped me off to just having them as sets in the file. 🤷‍♂️
