### ISSUE TITLE
Tests require network access

### ISSUE THREAD

**Issue by lilyball** [peterheesterman/chit#48]
**Describe the bug**
The `chit::details::alternatives::tests::can_parse_alternatives` test fails when run in a sandboxed environment because it requires network access. Unit tests shouldn't use network access.

```
  thread 'main' panicked at 'Alternative retrieval failed: ConnectionError(Error { kind: Hyper(Error { kind: Connect, cause: Custom { kind: Other, error: StringError("failed to lookup address information: Name or service not known") } }), url: Some("https://raw.githubusercontent.com/peterheesterman/chit/master/alternatives.json") })', src/libcore/result.rs:997:5
  note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
  
  
  failures:
      chit::details::alternatives::tests::can_parse_alternatives
  
  test result: FAILED. 12 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

**To Reproduce**
Run the unit tests in a sandbox that disallows network access.

**Expected behavior**
The unit tests should not rely on network access.

**Desktop (please complete the following information):**
Tested in NixOS

**Comment by peterheesterman** [comment]
I added this test in order to check that the `alternatives.json` file could be parsed. I am going to make this test pass while `offline`/`in a sandboxed` for now. 🤷‍♂ 

I think this is pragmatic, will circle round to it when a change is needed.

**Comment by lilyball** [comment]
Why do you need to load it from the network though? Just use include_file!() to pull it from the local source instead at compile-time.

**Comment by 8176135** [comment]
I was also working on this, however I changed it so that it parses the alternatives.json file in the root folder instead, making it fit the original `can_parse_alternatives` name, checking to see if it can parse the syntax or not.

**Comment by peterheesterman** [comment]
I have closed my PR. 

You don't need to, i was using the test to check that alternatives at `https://github.com/peterheesterman/chit/blob/master/alternatives.json` can be parsed incase i pushed something bad to it one day. I should write a completely separate check for that.

@8176135 nice, you got the real solutions. 👍
