### ISSUE TITLE
List Nix installation instructions in README

### ISSUE THREAD

**Issue by lilyball** [peterheesterman/chit#50]
As of [today](https://github.com/NixOS/nixpkgs/pull/61428) [Nix](https://nixos.org/nix/) now includes a package for Chit. It will probably take a few days before the package is available on the published channel, but once it is, it would be nice to have Nix installation instructions in the README.

**Comment by peterheesterman** [comment]
I am not a `Nix` user at the moment. I will need to have a look at how it works and then add the instructions. 👍 

Feel free to teach me how via a PR. 🤣 **Or** I would love a link to another project that does a really good job of explaining it i can use as a template. 💯

**Comment by lilyball** [comment]
The basic installation instructions is just `nix-env -iA chit` (`nix-env -i chit` works too but is slower, because it has to search by package name rather than attribute path).

**Comment by lilyball** [comment]
Scratch that I mean `nix-env -iA nixpkgs.chit`.
